export enum MessageEvent {
    MESSAGE_CREATED = 'message.created',
    CONVERSATION_JOINED = 'conversation.joined',
    CONVERSATION_CREATED = 'conversation.created',
    CONVERSATION_LEFT = 'conversation.left',
    COMMENT_CREATED = 'comment.created',
    LIKE_CREATED = 'like.created',
    REQUEST_FORUM_CREATED = 'request_forum.created',
    REQUEST_FORUM_APPROVED = 'request_forum.approved',
    REQUEST_POST_CREATED = 'request_post.created',
    REQUEST_POST_APPROVED = 'request_post.approved',
    REQUEST_FRIEND_CREATED = 'request_friend.created',
    REQUEST_FRIEND_APPROVED = 'request_friend.approved',
    REPLY_COMMENT_CREATED = 'reply_comment.created',
    FORUM_APPROVED = 'forum.approved',
    FRIENDSHIP_CREATED = 'friendship.created',
    EVENT_COMMENT_CREATED = 'event_comment.created',
    EVENT_UPCOMING = 'event.upcoming',
}